import { name } from './heroes.js';
import chalk from 'chalk';
import { writeFileSync, appendFileSync } from 'fs';
const myLog = 'console.log("This is appended text")';
writeFileSync('text.txt', 'console.log("working")');
appendFileSync('text.txt', myLog);
appendFileSync('text.txt', name.age);
appendFileSync('text.txt', name.hero);
console.log(chalk.blue.bgRed.bold('This is awesome'));
console.log(chalk.bgYellow.black.bold(name.hero));
